version: "3.5"

services:
  redis:
    image: redis:latest
    networks: 
      - redisnet

  django_wsgi:
    container_name: django_wsgi
    build: .
    command: uwsgi --socket=:9000 --module=seedesta.wsgi:application --py-autoreload=1
    volumes:
      - .:/code
    networks: 
      - webnet
      - redisnet
    links:
      - redis
  
  django_asgi:
    container_name: django_asgi
    build: .
    env_file:
      - .env
    command: daphne -b 0.0.0.0 -p 8000 seedesta.asgi:application
    volumes:
      - .:/code
    networks: 
      - webnet
      - redisnet
    links:
      - redis
  
  nginx:
    image: nginx:1.15.0
    depends_on:
      - django_asgi
      - django_wsgi
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - ./nginx:/etc/nginx/conf.d
      - ./static:/static
      - ./media:/media
    networks:
      - webnet
    ports:
      - "80:80"
      - 443:443

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

networks: 
  webnet:
  redisnet:
