from django.urls import path
from api.serializers import UserChangePasswordMobileSerializer
from . import views
from django.views.decorators.csrf import csrf_exempt
from .views import (RegisterUser, VerifyOTP, LoginUser, 
                    AppSliderView, ChangePasswordSendMail, 
                    ChangePasswordVerifyOTP, ChangePassword, 
                    UserProfileView, ResetPassword, UserProfilePic,
                    ContactUsView, AboutUsView, TermsConditionView,
                    PrivacyPolicyView, HelpView, NotificationsView,
                    TicketView, ProductView, MembersListing,
                    PaymentPlanView, GoalView, ProductDetailsView,
                    HomeSliderView, HomeAPIView, GoalDetailsView,
                    GoalUserView, FavouriteGoalView, UserDetailsView,
                    FavouriteUserView, FollowUserView, FollowRequestView,
                    RatingUserView, PostUserView, FollowingUserView,
                    UnFollowUserView, FavouritePostView, UserDetailsPageView,
                    GoalUserPersonalView,GroupGoalView, GroupGoalIndividualView,
                    MembersViewListing, PartipicentGoalView, ResendOTPView,
                    GoalMemberRequestView, GoalMemberListingView, FavouriteProductView,
                    RequestGoalView, RequestGoalMemberView, GoalMemberDetailsView,
                    GoalSubGoalsDetailsView, RoomView, ChatView, UserRoomView, UserChatView,
                    GroupGoalUserView, GroupChatView, PaymentView, GroupRoomChatView,
                    MobileLoginUser, VerifMobileyOTP, ChangePasswordSendMobileOTP,
                    ChangePasswordVerifyMobileOTP, ChangePasswordMobile, CheckPaymentStatusView,
                    PostLikeDislikeView, PostDetailsView, PostCountView, GoalOrderView,
                    CheckSocialUser, RegisterSocialUser, VendorHomeAPIView, GroupQuestionAPIView,
                    GoalQuestionAnswerAPIView, GoalCommentAPIView, GoalCommentRatingAPIView,
                    GroupAdminListing, GroupMemberListing, LocationView, LocationUpdateView,
                    PaymentTokenView, GoalDonationView, GoalLeaveRequestView, GoalAdminLeaveRequestView,
                    GoalPollView, RemoveGoalMemberView, VendorSubscriptionView, VendorSubscriptionPlanView,
                    CheckSubscriptionPaymentView, GoalPaymentPlanView, UserGoalSubscriptionView,
                    PaymentDefaultView, UserNotificationView, LogoutUser, PaypalView, VendorInvoiceView, 
                    VendorTransactionView, VendorTransactionHeadingView, CurrencyConvertorView)

urlpatterns = [
    # path('', views.homepage),
    path('goal-completed/', views.goalSubscriptionCompletedwebhook),
    #------------------------
    path('paypal-testing/', PaypalView.as_view()),
    #-----------------------
    path('register/', RegisterUser.as_view()),
    path('check-social-login/', CheckSocialUser.as_view()),
    path('register-social-account/', RegisterSocialUser.as_view()),
    path('login/', LoginUser.as_view()),
    path('logout-user/', LogoutUser.as_view()),
    path('verify/', VerifyOTP.as_view()),
    path('app-slider/', AppSliderView.as_view()),
    path('forget-password/', ChangePasswordSendMail.as_view()),
    path('verify-otp/', ChangePasswordVerifyOTP.as_view()),
    path('change-password/', ChangePassword.as_view()),
    path('edit-profile/', UserProfileView.as_view()),
    path('reset-password/', ResetPassword.as_view()),
    path('profile-pic/', UserProfilePic.as_view()),
    path('contact-us/', ContactUsView.as_view()),
    path('about-us/', AboutUsView.as_view()),
    path('terms&condition/', TermsConditionView.as_view()),
    path('privacy-policy/', PrivacyPolicyView.as_view()),
    path('help/', HelpView.as_view()),
    path('notification/', NotificationsView.as_view()),
    path('tickets/', TicketView.as_view()),
    path('products/', ProductView.as_view()),
    # path('products-list/', ProductListing.as_view()),
    path('members/', MembersListing.as_view()),
    path('plans/', PaymentPlanView.as_view()),
    path('goals/', GoalView.as_view()),
    path('product-details/', ProductDetailsView.as_view()),
    path('home-slider/', HomeSliderView.as_view()),
    path('home-api/', HomeAPIView.as_view()),
    path('goal-details/', GoalDetailsView.as_view()),
    path('user-goals/', GoalUserView.as_view()),
    path('favourite-goal/', FavouriteGoalView.as_view()),
    path('user-details/', UserDetailsView.as_view()),
    path('favourite-user/', FavouriteUserView.as_view()),
    path('follow-user/', FollowUserView.as_view()),
    path('follow-requests/', FollowRequestView.as_view()),
    path('user-ratings/', RatingUserView.as_view()),
    path('posts/', PostUserView.as_view()),
    path('following-user/', FollowingUserView.as_view()),
    path('unfollow-user/', UnFollowUserView.as_view()),
    path('favourite-posts/', FavouritePostView.as_view()),
    path('user-details-page/', UserDetailsPageView.as_view()),
    path('user-personal-goals/', GoalUserPersonalView.as_view()),
    path('group-goal/', GroupGoalView.as_view()),
    path('individual-goal/', GroupGoalIndividualView.as_view()),
    path('members-listing/', MembersViewListing.as_view()),
    path('participient-goals/', PartipicentGoalView.as_view()),
    path('resend-otp/', ResendOTPView.as_view()),
    path('goal-requests/', GoalMemberRequestView.as_view()),
    path('goal-members/', GoalMemberListingView.as_view()),
    path('favourite-products/', FavouriteProductView.as_view()),
    path('goal-request-member/', RequestGoalView.as_view()),
    path('goal-request-member-view/', RequestGoalMemberView.as_view()),
    path('goal-member-details/', GoalMemberDetailsView.as_view()),
    path('subgoals-listing/', GoalSubGoalsDetailsView.as_view()),
    path('rooms/', RoomView.as_view()),
    path('chats/', ChatView.as_view()),
    path('user-chats/', UserRoomView.as_view()),
    path('user-chats-view/', UserChatView.as_view()),
    path('user-group-goal/', GroupGoalUserView.as_view()),
    path('group-chat-view/', GroupChatView.as_view()),
    path('payment/goals/', PaymentView.as_view()),
    path('group-chat-room/', GroupRoomChatView.as_view()),
    path('mobile-login/', MobileLoginUser.as_view()),
    path('verify-mobile-otp/', VerifMobileyOTP.as_view()),
    path('send-mobile-otp/', ChangePasswordSendMobileOTP.as_view()),
    path('verify-changepassword-mobile-otp/', ChangePasswordVerifyMobileOTP.as_view()),
    path('reset-password-mobile/', ChangePasswordMobile.as_view()),
    path('check-payment-status/', CheckPaymentStatusView.as_view()),
    path('post-like-status/', PostLikeDislikeView.as_view()),
    path('post-details-view/', PostDetailsView.as_view()),
    path('post-count-view/', PostCountView.as_view()),
    path('group-questions/', GroupQuestionAPIView.as_view()),
    path('goal-questions&answer/', GoalQuestionAnswerAPIView.as_view()),
    path('goal-comments/', GoalCommentAPIView.as_view()),
    path('goal-comment-rating/', GoalCommentRatingAPIView.as_view()),
    path('group-admin-listing/', GroupAdminListing.as_view()),
    path('group-member-listing/', GroupMemberListing.as_view()),
    path('location-view/', LocationView.as_view()),
    path('location-update/', LocationUpdateView.as_view()),
    path('card-token/', PaymentTokenView.as_view()),
    path('donation-payment/', GoalDonationView.as_view()),
    path('goal-leave-request/', GoalLeaveRequestView.as_view()),
    path('goal-admin-leave-request/', GoalAdminLeaveRequestView.as_view()),
    path('goal-poll/', GoalPollView.as_view()),
    path('remove-goal-member/', RemoveGoalMemberView.as_view()),
    path('goal-payment-plan/', GoalPaymentPlanView.as_view()),
    path('goal-subscription-plan-details/', UserGoalSubscriptionView.as_view()),
    path('set-default-payment/', PaymentDefaultView.as_view()),
    path('user-notifications/', UserNotificationView.as_view()),

#------------vendors----------------
    path('goal-orders/', GoalOrderView.as_view()),
    path('vendor-home/', VendorHomeAPIView.as_view()),
    path('vendor-subscription/', VendorSubscriptionView.as_view()),
    path('vendor-subscription-plan/', VendorSubscriptionPlanView.as_view()),
    path('check-vendor-subscription-payment/', CheckSubscriptionPaymentView.as_view()),
    path('vendor-invoice/', VendorInvoiceView.as_view()),
    path('vendor-transactions/', VendorTransactionView.as_view()),
    path('vendor-transactions-heading/', VendorTransactionHeadingView.as_view()),

#-----------------payment-status---------------
    path('payment-success/', views.payment_success, name='payment_success'),
    path('payment-failed/', views.payment_failed, name='payment_failed'),
    path('currencyConvertor/', CurrencyConvertorView.as_view(),),
]